-- MySQL Script generated by MySQL Workbench
-- jue 17 sep 2015 02:40:04 PET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbnoticias
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dbnoticias` ;

-- -----------------------------------------------------
-- Schema dbnoticias
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbnoticias` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `dbnoticias` ;

-- -----------------------------------------------------
-- Table `dbnoticias`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbnoticias`.`user` ;

CREATE TABLE IF NOT EXISTS `dbnoticias`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `username` varchar(16) NOT NULL,
  `email` varchar(255) NULL,
  `password` varchar(32) NOT NULL,
  `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `name` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `score` INT NULL,
  `steamid` VARCHAR(45) NULL,
  `facebookid` VARCHAR(45) NULL,
  `profile_info` VARCHAR(45) NULL,
  PRIMARY KEY (`iduser`));


-- -----------------------------------------------------
-- Table `dbnoticias`.`article`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbnoticias`.`article` ;

CREATE TABLE IF NOT EXISTS `dbnoticias`.`article` (
  `idarticle` INT NOT NULL AUTO_INCREMENT,
  `score` INT NULL,
  `title` TEXT NULL,
  `text` TEXT NULL,
  `numviews` INT NULL,
  `user_iduser` INT NOT NULL,
  `ts_create` DATE,
  `ts_update` DATE NULL,
  PRIMARY KEY (`idarticle`),
  INDEX `fk_article_user1_idx` (`user_iduser` ASC),
  CONSTRAINT `fk_article_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `dbnoticias`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbnoticias`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbnoticias`.`comment` ;

CREATE TABLE IF NOT EXISTS `dbnoticias`.`comment` (
  `idcomment` INT NOT NULL AUTO_INCREMENT,
  `TEXT` TEXT NULL,
  `score` INT NULL,
  `article_idarticle` INT NOT NULL,
  `user_iduser` INT NULL,
  PRIMARY KEY (`idcomment`),
  INDEX `fk_comment_article1_idx` (`article_idarticle` ASC),
  INDEX `fk_comment_user1_idx` (`user_iduser` ASC),
  CONSTRAINT `fk_comment_article1`
    FOREIGN KEY (`article_idarticle`)
    REFERENCES `dbnoticias`.`article` (`idarticle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `dbnoticias`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbnoticias`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbnoticias`.`category` ;

CREATE TABLE IF NOT EXISTS `dbnoticias`.`category` (
  `idcategory` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idcategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbnoticias`.`topic_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbnoticias`.`topic_category` ;

CREATE TABLE IF NOT EXISTS `dbnoticias`.`topic_category` (
  `idtopic_category` INT NOT NULL AUTO_INCREMENT,
  `articleid` INT NULL,
  PRIMARY KEY (`idtopic_category`),
  INDEX `fk_article_idx` (`articleid` ASC),
  CONSTRAINT `fk_topic_join`
    FOREIGN KEY (`idtopic_category`)
    REFERENCES `dbnoticias`.`category` (`idcategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article`
    FOREIGN KEY (`articleid`)
    REFERENCES `dbnoticias`.`article` (`idarticle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
